const SHIPMENT_STATUS = Object.freeze({
  LABEL_CREATED: "LABEL_CREATED",
  PICKED_UP: "PICKED_UP",
  IN_TRANSIT: "IN_TRANSIT",
  OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
  DELIVERED: "DELIVERED",
  RETURNED: "RETURNED",
});

/** Allowed forward transitions */
const SHIPMENT_TRANSITIONS = Object.freeze({
  LABEL_CREATED: ["PICKED_UP"],
  PICKED_UP: ["IN_TRANSIT"],
  IN_TRANSIT: ["OUT_FOR_DELIVERY", "RETURNED"],
  OUT_FOR_DELIVERY: ["DELIVERED", "RETURNED"],
  DELIVERED: [],
  RETURNED: [],
});

module.exports = { SHIPMENT_STATUS, SHIPMENT_TRANSITIONS };
